### ISSUE TITLE
HTTP(S) Proxy | Agent With OhMyFetch

### ISSUE THREAD

**Issue by BlackYuzia** [unjs/ofetch#161]
Hi there.

Just a short question.
**How we could use `ohmyfetch` with HTTP(S) Proxy | Agent?**

For example.
If we use `axios`, we could use `options.httpsAgent` with [**httpsAgent**](https://www.npmjs.com/package/https-proxy-agent)

In `ohmyfetch`I didn't find any docs about proxy and/or `httpsAgent`

**Comment by yuyinws** [comment]
Need this too.

**Comment by yuyinws** [comment]
It's works for me
```ts
import { Agent } from 'node:http'
import { $fetch } from 'ohmyfetch'

const agent = new Agent({
    host: '127.0.0.1',
    port: 7890,
})

$fetch(url, {
  agent: agent
})
```

**Comment by yuyinws** [comment]
It's works for me on node 16.X

```ts
import HttpsProxyAgent from 'https-proxy-agent'
import { ofetch } from 'ofetch'

await ofetch('user',{
 agent: new HttpsProxyAgent('http://127.0.0.1:7890')
})
```

**Comment by Rekryt** [comment]
Try use changeOrigin
```
devProxy: {
    ...
    '/proxy/example': { target: 'https://example.com', changeOrigin: true }
}
```

**Comment by BlackYuzia** [comment]
Yes, this worked for me too. Thx.

**Comment by pi0** [comment]
PR welcome to the docs.

**Comment by 289997171** [comment]
server\api\test\google.get.ts
```javascript
import {HttpsProxyAgent} from "https-proxy-agent";
import {$fetch, ofetch} from "ofetch";
const agent = new HttpsProxyAgent('http://127.0.0.1:7890')

export default defineEventHandler(async (event) => {
    // const res = await ofetch('https://www.google.com', {
    //     agent: agent
    // })
    const res = await $fetch('https://www.google.com', {
        agent: agent
    })
    console.log(res);
    return res
})
```
curl test request
```cmd
curl http://localhost:3000/api/test/google

{"url":"/api/test/google","statusCode":500,"statusMessage":"","message":"[GET] \"https://www.google.com\": <no response> fetch failed","stack":"<pre><span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>\n<span class=\"stack internal\">at async $fetchRaw2 (/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:228:14)</span>\n<span class=\"stack internal\">at async $fetch2 (/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:261:15)</span>\n<span class=\"stack\">at <anonymous> (\\server\\api\\test\\google.get.ts:9:1)</span>\n<span class=\"stack internal\">at async Object.handler (/node_modules/h3/dist/index.mjs:1675:19)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (/node_modules/h3/dist/index.mjs:1885:7)</span></pre>"}
C:\Users\Administrator>
```
I'm use 'Clash for windows', I have tested with java http proxy, and it work fine. but i dont know why it not work with ofetch or $fetch.
