### ISSUE TITLE
How to get a specify error timeout?

### ISSUE THREAD

**Issue by maicss** [unjs/ofetch#310]
### Environment

ofetch: 1.3.3
nodejs: 19.7.0
nuxt: 3.8.0

### Reproduction

use $fetch to call an API, when fetch timeout, promise error:
```
error.code: undefined
error.message: [GET] "https://api.themoviedb.org/3/movie/575264?language=zh-CN": <no response>
JSON.stringify(error): {"name":"FetchError"}
error.cause: TypeError: fetch failed
```

### Describe the bug

```
FetchError: [GET] "https://api.themoviedb.org/3/movie/575264?language=zh-CN": <no response> fetch failed
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $fetchRaw2 (file:///xxx/node_modules/.pnpm/ofetch@1.3.3/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:228:14)
    ... 3 lines matching cause stack trace ...
    at async Server.toNodeHandle (file:///xxx/node_modules/.pnpm/h3@1.8.2/node_modules/h3/dist/index.mjs:1840:7) {
  [cause]: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11413:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async $fetchRaw2 (file:///xxx/node_modules/.pnpm/ofetch@1.3.3/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:219:26)
      at async $fetchRaw2 (file:///xxx/node_modules/.pnpm/ofetch@1.3.3/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:228:14)
      at async $fetch2 (file:///xxx/node_modules/.pnpm/ofetch@1.3.3/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:261:15)
      at <anonymous> (C:\Users\ASUS\workspace\nas-tools\server\api\tmdb\[...].ts:123:1)
      at async Object.handler (file:///xxx/node_modules/.pnpm/h3@1.8.2/node_modules/h3/dist/index.mjs:1630:19)
      at async Server.toNodeHandle (file:///xxx/node_modules/.pnpm/h3@1.8.2/node_modules/h3/dist/index.mjs:1840:7) {
    cause: ConnectTimeoutError: Connect Timeout Error
        at onConnectTimeout (node:internal/deps/undici/undici:8380:28)
        at node:internal/deps/undici/undici:8338:50
        at Immediate._onImmediate (node:internal/deps/undici/undici:8367:37)
        at process.processImmediate (node:internal/timers:475:21) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }
}
```
server side log has information of `ConnectTimeoutError` or `UND_ERR_CONNECT_TIMEOUT` is useful, how can I get this infomation?

**Comment by nari** [comment]
I got same problem...

**Comment by zpzxgcr** [comment]
+1

**Comment by zpzxgcr** [comment]
@pi0 help

**Comment by lxl66566** [comment]
+1

**Comment by vicentematus** [comment]
@zpzxgcr  @maicss  @lxl66566  @nari  I faced the same problem when trying to get the timeout error. In older versions of Nuxt, `ofetch` doesn't raise an special `Error` for these cases. It just throws a `FetchError`. 

In that case you can map the `Connection Timeout Error` asking for the string of the `error.message`:

```typescript
if (error.name === "FetchError") {
    if(error.status === 408) {
    // Request Timeout
    }
     
    if(error.status === 504){
    // Gateway Timeout Error
    }

	if (error.message.includes("<no response> This operation was aborted")) {
	  // Here we are sure that it's a timeout error after asking for possible statuses
	  console.error("[Timeout] The request has exceeded the maximum waiting time allowed by the client. Please try again. ")
	}
}
```

I know using string manipulation for getting errors is not the most precise, but it works.
