### ISSUE TITLE
Multipart image upload not working with fetch but with RapidAPI

### ISSUE THREAD

**Issue by FrazeColder** [unjs/ofetch#388]
Hey there, 
for whatever reason, I am not able to upload the image to my server. But when doing it with RapidAPI and with the exact same image, it works. What am I doing wrong here?

QuillEditor code:
```
<template>
  <QuillEditor :modules="modules" :toolbar="toolbar" theme="snow" toolbar="full" />
</template>

<script>
import { QuillEditor } from '@vueup/vue-quill'
import '@vueup/vue-quill/dist/vue-quill.snow.css';
import ImageUploader from "quill-image-uploader";
const runtimeConfig = useRuntimeConfig();
const { fetch } = useSmartFetch();

export default {
  setup: () => {
    const toolbar = [
      ['image', 'link'],
      ['emoji']
    ];
    const modules = {
      name: "imageUploader",
      module: ImageUploader,
      options: {
        upload: (file) => {
          return new Promise(async (resolve, reject) => {
            const formData = new FormData()
            formData.append('image', file);

            console.log(file)
            console.log(formData)

            const authStore = useAuthStore()
            const response = await $fetch(runtimeConfig.public.api.image.upload, {
              method: 'POST',
              body: formData,
              headers: {
                'Authorization': 'Bearer ' + authStore.accessToken,
                'Content-Type': 'multipart/form-data'
              }
            })


          });
        },
      },
    };

    return { toolbar, modules };
  },
  components: {
    QuillEditor,
  },
};
</script>

```

When I inspect my request, I have set my Bearer token to authenticate (otherwise I would get an 401 instead of an 422) as well as ```Content-Type: multipart/form-data```. Even my payload contains the form data. This is the beginning of my payload:
```
-----------------------------118964521239883964394155378140
Content-Disposition: form-data; name="image"; filename="1705385217523.jpg"
Content-Type: image/jpeg
...
...
...
```

However, in Laravel Telescope my payload is empty:
<img width="1178" alt="3fetch" src="https://github.com/NoelOConnell/quill-image-uploader/assets/18104426/4fb93444-ca24-4be4-acb3-2783d7316c29">

When doing the exact same with RapidAPI:
<img width="507" alt="1RapidAPI" src="https://github.com/NoelOConnell/quill-image-uploader/assets/18104426/3e42598e-1796-4a36-ba09-1761ec8208b1">

Everything works without any problem. Also, the payload is set:
<img width="1176" alt="2RapidApi" src="https://github.com/NoelOConnell/quill-image-uploader/assets/18104426/d1730d8c-8bc2-408d-8dd5-7b902a9f829c">

How can this be? I am pretty sure my backend works, it's tested. But I am also sure I am doing the request correctly. 
Can anybody help me?

Kind regards

**Comment by GuppyTheCat** [comment]
Seems like i have same problem when uploading big files( >100Mb ).
Nuxt frontend sends file and i can see payload in browser, but nuxt server api fails to read it with readMultipartFormData.
Sending file straight to remote api works fine.

**Comment by pi0** [comment]
Please please share a minimal reproduction (or at least any runnable one) in order to allow investigating such issues. 🙏🏼

**Comment by GuppyTheCat** [comment]
> Please please share a minimal reproduction (or at least any runnable one) in order to allow investigating such issues. 🙏🏼

Here is reproduction - [file-upload-test](https://github.com/GuppyTheCat/file-upload-test)
On button click you choose file and it should automatically upload.
There is just upload to the server api and reading form data but it is enough.
If you try to upload files approximately larger than 100Mb, upload will fail.

I get this error:
```Reading multipart form data...
Error reading multipart form data: Invalid array length

  at Array.push (<anonymous>)
  at parse (node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:196:16)
  at readMultipartFormData (node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:469:10)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at Object.handler (server/api/upload.post.ts:4:1)
  at async node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:1975:19
  at async Object.callAsync (node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:2266:7)```

**Comment by GuppyTheCat** [comment]
Sorry, there is problem with h3, i suppose.
